'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Plane, ShieldCheck, ArrowRight, CheckCircle2, Building2, GraduationCap, Globe2, FileText, Users, Mail, Phone, MapPin } from 'lucide-react';
import { t, Lang } from '@/lib/i18n';

const requirements = ['Ugandan citizen or eligible resident applicant','Age normally 17–28 for cadet pathway priority review','Completed secondary school; diploma or degree preferred','Strong English communication ability','Able to pass aviation medical, background and aptitude screening','Clear family support or financing plan where required','Long-term commitment to an airline pilot career'];
const process = ['Submit online cadet interest form','Initial eligibility and document review by Stratus','English, aptitude and medical pre-screening','Airline partner final review where applicable','Conditional pathway offer before training commencement'];
const cards = [[Building2,'Airline-aligned','Designed around airline cockpit staffing needs.'],[GraduationCap,'Cadet-focused','Supports high-potential local students from zero experience.'],[Globe2,'Regional Vision','Built for Uganda first, then East African expansion.']];

export default function Home(){
  const [lang,setLang]=useState<Lang>('en');
  const copy=t[lang];
  const [sent,setSent]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();
    const fd=new FormData(e.currentTarget);
    const payload=Object.fromEntries(fd.entries());
    await fetch('/api/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload, lang})});
    setSent(true);
    const msg=encodeURIComponent(`New Stratus Cadet Application\nName: ${payload.fullName}\nPhone: ${payload.phone}\nEmail: ${payload.email}\nCitizenship: ${payload.citizenship}`);
    window.open(`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '256700000000'}?text=${msg}`,'_blank');
  }
  return <main>
    <nav className="nav"><div className="container navin"><div className="brand"><div className="logo"><Plane size={22}/></div><div><b>Stratus Aviation Group</b><div className="muted" style={{fontSize:12,letterSpacing:3}}>UGANDA CADET PATHWAY</div></div></div><div className="links"><a href="#about">{copy.navAbout}</a><a href="#pathway">{copy.navPathway}</a><a href="#airlines">{copy.navPartners}</a><a href="#apply">{copy.navApply}</a><a href="/admin">{copy.navAdmin}</a><select className="lang" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">English</option><option value="zh">中文</option><option value="fr">Français</option></select></div><a className="btn white" href="#apply">{copy.cta}</a></div></nav>
    <section className="hero"><div className="container grid2"><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="eyebrow"><ShieldCheck size={16}/>{copy.heroBadge}</div><h1 className="h1">{copy.heroTitle}</h1><p className="lead">{copy.heroText}</p><div style={{display:'flex',gap:14,marginTop:30,flexWrap:'wrap'}}><a className="btn primary" href="#apply">{copy.cta}<ArrowRight size={18}/></a><a className="btn ghost" href="#pathway">{copy.view}</a></div></motion.div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.12}} className="panel"><div className="panel-inner"><div className="status"><div><div className="muted">Cadet Pipeline</div><h2>{copy.status}</h2></div><div className="pill">{copy.open}</div></div><div className="list">{['Initial Screening','Medical & Aptitude','Training Pathway','Airline Placement'].map(x=><div className="listitem" key={x}><CheckCircle2 color="#7dd3fc"/><div><b>{x}</b><div className="muted">Professional review and pathway coordination</div></div></div>)}</div></div></motion.div></div></section>
    <section id="about" className="section"><div className="container grid2"><div><div className="muted">ABOUT STRATUS</div><h2 style={{fontSize:42}}>{copy.aboutTitle}</h2></div><div><p className="lead">{copy.aboutText}</p><div className="cards" style={{marginTop:26}}>{cards.map(([Icon,title,desc]:any)=><motion.div whileHover={{y:-6}} className="card" key={title}><Icon color="#7dd3fc"/><h3>{title}</h3><p className="muted">{desc}</p></motion.div>)}</div></div></div></section>
    <section id="pathway" className="section band"><div className="container"><div style={{maxWidth:760}}><div className="muted">CADET PATHWAY</div><h2 style={{fontSize:42}}>{copy.pathwayTitle}</h2><p className="lead">{copy.pathwayText}</p></div><div className="grid2" style={{marginTop:32}}><div className="card"><Users color="#7dd3fc"/><h2>{copy.req}</h2>{requirements.map(r=><div className="listitem" key={r}><CheckCircle2 color="#86efac" size={20}/><span>{r}</span></div>)}</div><div className="card"><FileText color="#7dd3fc"/><h2>{copy.process}</h2>{process.map((p,i)=><div className="listitem" key={p}><b className="logo" style={{width:34,height:34,borderRadius:999,fontSize:13}}>{i+1}</b><span>{p}</span></div>)}</div></div></div></section>
    <section id="airlines" className="section"><div className="container"><h2 style={{fontSize:42}}>{copy.partnersTitle}</h2><p className="lead">{copy.partnersText}</p><div className="cards" style={{marginTop:28}}>{['Uganda Airlines','Approved Training Partners','Future Regional Airlines'].map((x,i)=><div className="card" key={x}><div style={{height:92,borderRadius:22,background:'linear-gradient(135deg,rgba(255,255,255,.14),rgba(255,255,255,.03))',border:'1px solid rgba(255,255,255,.1)'}}/><h3>{x}</h3><p className="muted">{i===0?'National carrier pathway focus.':i===1?'ICAO-standard training delivery.':'East Africa scalable expansion.'}</p></div>)}</div></div></section>
    <section id="apply" className="section formwrap"><div className="container grid2"><div><div className="muted">CADET APPLICATION</div><h2 style={{fontSize:42}}>{copy.applyTitle}</h2><p className="lead">{copy.applyText}</p><p className="listitem"><Mail size={20}/> admissions@stratusaviationgroup.com</p><p className="listitem"><Phone size={20}/> WhatsApp number set in deployment</p><p className="listitem"><MapPin size={20}/> Kampala, Uganda / Vancouver, Canada</p></div><form className="formcard" onSubmit={submit}><h2>Cadet Interest Form</h2><div className="formgrid"><label className="full">{copy.fields.citizenship}<select name="citizenship"><option>Ugandan Citizen</option><option>Ugandan Resident</option><option>Non-Ugandan Applicant</option></select></label><Field name="fullName" label={copy.fields.fullName}/><Field name="phone" label={copy.fields.phone}/><Field name="email" label={copy.fields.email}/><Field name="birthYear" label={copy.fields.birthYear}/><Field name="age" label={copy.fields.age}/><label>{copy.fields.education}<select name="education"><option>Secondary School</option><option>Diploma</option><option>Bachelor Degree</option><option>Master Degree or above</option></select></label><label>{copy.fields.english}<select name="englishLevel"><option>Basic</option><option>Intermediate</option><option>Advanced</option><option>Fluent</option></select></label><label>{copy.fields.medical}<select name="medicalStatus"><option>Already passed aviation medical</option><option>Not yet, willing to take exam</option><option>Unsure</option></select></label><label>{copy.fields.experience}<select name="flightExperience"><option>Zero flight hours</option><option>1–50 flight hours</option><option>50+ flight hours</option><option>Already hold a pilot licence</option></select></label><label className="full">{copy.fields.motivation}<textarea name="motivation" rows={5}/></label></div><button className="btn primary" style={{width:'100%',justifyContent:'center',marginTop:20}}>{copy.submit}<ArrowRight size={18}/></button>{sent&&<p style={{color:'#059669',fontWeight:800}}>Application received. WhatsApp window opened.</p>}<p className="muted" style={{fontSize:12}}>{copy.disclaimer}</p></form></div></section>
    <footer><div className="container">© 2026 Stratus Aviation Group Limited. All rights reserved.</div></footer>
  </main>
}
function Field({name,label}:{name:string,label:string}){return <label>{label}<input name={name} required/></label>}
